package com.example.contadordebirras.domain.achievements

object AchievementCatalog {
    val achievements = listOf(
        AchievementDefinition(
            id = "GEN_001",
            category = "General",
            name = "Chavalo pusilánime",
            description = "Registrar 1 cerveza total",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Vaso pequeño",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "GEN_002",
            category = "General",
            name = "Primer pelo en el bigote",
            description = "Registrar 3 cervezas totales",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Tres marcas",
            isHidden = false,
            target = 3
        ),
        AchievementDefinition(
            id = "GEN_003",
            category = "General",
            name = "Decena dorada",
            description = "Registrar 10 cervezas totales",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Medalla 10",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "GEN_004",
            category = "General",
            name = "Pequeña barrica",
            description = "Registrar 25 cervezas totales",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Barril pequeño",
            isHidden = false,
            target = 25
        ),
        AchievementDefinition(
            id = "GEN_005",
            category = "General",
            name = "Medio centenar espumoso",
            description = "Registrar 50 cervezas totales",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Jarra con corona",
            isHidden = false,
            target = 50
        ),
        AchievementDefinition(
            id = "GEN_006",
            category = "General",
            name = "Protoalemander",
            description = "Registrar 75 cervezas totales",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Espuma grande",
            isHidden = false,
            target = 75
        ),
        AchievementDefinition(
            id = "GEN_007",
            category = "General",
            name = "Como cien soles",
            description = "Registrar 100 cervezas totales",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Copa trofeo",
            isHidden = false,
            target = 100
        ),
        AchievementDefinition(
            id = "GEN_008",
            category = "General",
            name = "El camarero conoce tu nombre",
            description = "Registrar 150 cervezas totales",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Archivador",
            isHidden = false,
            target = 150
        ),
        AchievementDefinition(
            id = "GEN_009",
            category = "General",
            name = "Jodedor de birra",
            description = "Registrar 200 cervezas totales",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Barril grande",
            isHidden = false,
            target = 200
        ),
        AchievementDefinition(
            id = "GEN_010",
            category = "General",
            name = "Pelograsa",
            description = "Registrar 300 cervezas totales",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Vitrina",
            isHidden = false,
            target = 300
        ),
        AchievementDefinition(
            id = "GEN_011",
            category = "General",
            name = "Comercial de jamón al corte",
            description = "Registrar 500 cervezas totales",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Taburete con aura",
            isHidden = false,
            target = 500
        ),
        AchievementDefinition(
            id = "GEN_012",
            category = "General",
            name = "Recaudador de tragaperras",
            description = "Registrar 750 cervezas totales",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Catedral",
            isHidden = false,
            target = 750
        ),
        AchievementDefinition(
            id = "GEN_013",
            category = "General",
            name = "Divorciado después de los 50",
            description = "Registrar 1000 cervezas totales",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Libro antiguo",
            isHidden = false,
            target = 1000
        ),
        AchievementDefinition(
            id = "CAN_001",
            category = "Caña",
            name = "José Cañas",
            description = "Registrar 1 caña",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Caña pequeña",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "CAN_002",
            category = "Caña",
            name = "Caña vieja",
            description = "Registrar 10 cañas",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Bandeja",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "CAN_003",
            category = "Caña",
            name = "Player",
            description = "Registrar 25 cañas",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Tirador",
            isHidden = false,
            target = 25
        ),
        AchievementDefinition(
            id = "CAN_004",
            category = "Caña",
            name = "Jodedor de cañas",
            description = "Registrar 50 cañas",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Fila de vasos",
            isHidden = false,
            target = 50
        ),
        AchievementDefinition(
            id = "CAN_005",
            category = "Caña",
            name = "Pensionista",
            description = "Registrar 100 cañas",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Tirador dorado",
            isHidden = false,
            target = 100
        ),
        AchievementDefinition(
            id = "LAT_001",
            category = "Lata",
            name = "Abrelatas",
            description = "Registrar 1 lata",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Lata abierta",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "LAT_002",
            category = "Lata",
            name = "Carrefour en lata",
            description = "Registrar 10 latas",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Anilla",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "LAT_003",
            category = "Lata",
            name = "Chin sidoso con tarjeta",
            description = "Registrar 25 latas",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Torre de latas",
            isHidden = false,
            target = 25
        ),
        AchievementDefinition(
            id = "LAT_004",
            category = "Lata",
            name = "Rapero de banco",
            description = "Registrar 50 latas",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Estantería",
            isHidden = false,
            target = 50
        ),
        AchievementDefinition(
            id = "LAT_005",
            category = "Lata",
            name = "Pandemias",
            description = "Registrar 100 latas",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Anilla con corona",
            isHidden = false,
            target = 100
        ),
        AchievementDefinition(
            id = "BOT_001",
            category = "Botellín",
            name = "Chin-chín de cristal",
            description = "Registrar 1 botellín",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Botellín",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "BOT_002",
            category = "Botellín",
            name = "No chupes",
            description = "Registrar 10 botellines",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Botella con etiqueta",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "BOT_003",
            category = "Botellín",
            name = "Saca cacahuetes",
            description = "Registrar 25 botellines",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Caja de botellines",
            isHidden = false,
            target = 25
        ),
        AchievementDefinition(
            id = "BOT_004",
            category = "Botellín",
            name = "Fondo de nevera",
            description = "Registrar 50 botellines",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Nevera llena",
            isHidden = false,
            target = 50
        ),
        AchievementDefinition(
            id = "BOT_005",
            category = "Botellín",
            name = "Sácame un vasico anda majo",
            description = "Registrar 100 botellines",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Chapa estrella",
            isHidden = false,
            target = 100
        ),
        AchievementDefinition(
            id = "COP_001",
            category = "Copa",
            name = "Debut",
            description = "Registrar 1 copa",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Copa fina",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "COP_002",
            category = "Copa",
            name = "Copa menstrual",
            description = "Registrar 10 copas",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Copa con espuma",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "COP_003",
            category = "Copa",
            name = "Copa Konami",
            description = "Registrar 25 copas",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Copa especial",
            isHidden = false,
            target = 25
        ),
        AchievementDefinition(
            id = "COP_004",
            category = "Copa",
            name = "Copón",
            description = "Registrar 50 copas",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Copa en pedestal",
            isHidden = false,
            target = 50
        ),
        AchievementDefinition(
            id = "COP_005",
            category = "Copa",
            name = "Golfo de época",
            description = "Registrar 100 copas",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Copa trofeo",
            isHidden = false,
            target = 100
        ),
        AchievementDefinition(
            id = "JAR_001",
            category = "Jarra",
            name = "Primera jarra",
            description = "Registrar 1 jarra",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Jarra",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "JAR_002",
            category = "Jarra",
            name = "El tuno",
            description = "Registrar 10 jarras",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Mano con jarra",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "JAR_003",
            category = "Jarra",
            name = "Letón en Eurovisión",
            description = "Registrar 25 jarras",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Jarra grande",
            isHidden = false,
            target = 25
        ),
        AchievementDefinition(
            id = "JAR_004",
            category = "Jarra",
            name = "Septiembre llega con su ¡Oh dios mío!",
            description = "Registrar 50 jarras",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Jarra gigante",
            isHidden = false,
            target = 50
        ),
        AchievementDefinition(
            id = "JAR_005",
            category = "Jarra",
            name = "Frees en Cruz-Roja",
            description = "Registrar 100 jarras",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Jarra vikinga",
            isHidden = false,
            target = 100
        ),
        AchievementDefinition(
            id = "PIN_001",
            category = "Pinta",
            name = "Pinta inaugural",
            description = "Registrar 1 pinta",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Vaso de pinta",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "PIN_002",
            category = "Pinta",
            name = "Pintaza",
            description = "Registrar 10 pintas",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Pinta con rayo",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "PIN_003",
            category = "Pinta",
            name = "Territorio pub",
            description = "Registrar 25 pintas",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Cartel de pub",
            isHidden = false,
            target = 25
        ),
        AchievementDefinition(
            id = "PIN_004",
            category = "Pinta",
            name = "La pinta perfecta",
            description = "Registrar 50 pintas",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Pinta brillante",
            isHidden = false,
            target = 50
        ),
        AchievementDefinition(
            id = "PIN_005",
            category = "Pinta",
            name = "Lord de la pinta",
            description = "Registrar 100 pintas",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Pinta con corona",
            isHidden = false,
            target = 100
        ),
        AchievementDefinition(
            id = "LIT_001",
            category = "Litro",
            name = "Formato serio",
            description = "Registrar 1 litro",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Vaso grande",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "LIT_002",
            category = "Litro",
            name = "Litro registrado",
            description = "Registrar 5 litros",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Medidor",
            isHidden = false,
            target = 5
        ),
        AchievementDefinition(
            id = "LIT_003",
            category = "Litro",
            name = "Bebo litratos",
            description = "Registrar 10 litros",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Pesa",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "LIT_004",
            category = "Litro",
            name = "Maestro Sho-Hai",
            description = "Registrar 25 litros",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Tanque",
            isHidden = false,
            target = 25
        ),
        AchievementDefinition(
            id = "LIT_005",
            category = "Litro",
            name = "Desgraciao",
            description = "Registrar 50 litros",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Barril con escudo",
            isHidden = false,
            target = 50
        ),
        AchievementDefinition(
            id = "UBI_001",
            category = "Ubicación",
            name = "Primer sitio registrado",
            description = "Registrar primera ubicación",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Pin",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "UBI_002",
            category = "Ubicación",
            name = "Bar de confianza",
            description = "5 registros en el mismo lugar",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Bar",
            isHidden = false,
            target = 5
        ),
        AchievementDefinition(
            id = "UBI_003",
            category = "Ubicación",
            name = "Territorio conocido",
            description = "10 registros en el mismo lugar",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Mapa marcado",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "UBI_004",
            category = "Ubicación",
            name = "Ruta de bares",
            description = "Registrar 5 ubicaciones distintas",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Ruta",
            isHidden = false,
            target = 5
        ),
        AchievementDefinition(
            id = "UBI_005",
            category = "Ubicación",
            name = "Explorador local",
            description = "Registrar 10 ubicaciones distintas",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Brújula",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "UBI_006",
            category = "Ubicación",
            name = "Cervecero viajero",
            description = "Registrar en 2 ciudades distintas",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Maleta",
            isHidden = false,
            target = 2
        ),
        AchievementDefinition(
            id = "UBI_007",
            category = "Ubicación",
            name = "Fuera de casa",
            description = "Registrar en una ciudad nueva",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Señal",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "UBI_008",
            category = "Ubicación",
            name = "Mapa espumoso",
            description = "Registrar en 25 ubicaciones distintas",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Mapa completo",
            isHidden = false,
            target = 25
        ),
        AchievementDefinition(
            id = "UBI_009",
            category = "Ubicación",
            name = "Kilómetro cero",
            description = "Tener una ubicación más repetida",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Pin dorado",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "UBI_010",
            category = "Ubicación",
            name = "Nueva sede",
            description = "Cambiar la ubicación más frecuente",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Cartel nuevo",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "FOT_001",
            category = "Fotos",
            name = "Foto de archivo",
            description = "Añadir primera foto a una cerveza",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Cámara",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "FOT_002",
            category = "Fotos",
            name = "Galería de espuma",
            description = "Añadir 10 fotos",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Álbum",
            isHidden = false,
            target = 10
        ),
        AchievementDefinition(
            id = "FOT_003",
            category = "Fotos",
            name = "La cámara primero",
            description = "Añadir una foto desde la cámara",
            difficulty = AchievementDifficulty.COMUN,
            points = 5,
            iconKey = "Cámara frontal",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "FOT_004",
            category = "Fotos",
            name = "Recuerdo desbloqueado",
            description = "Abrir una cerveza antigua con foto",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Polaroid",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "FOT_005",
            category = "Fotos",
            name = "Reportero de barra",
            description = "Añadir 25 fotos",
            difficulty = AchievementDifficulty.RARO,
            points = 20,
            iconKey = "Cámara pro",
            isHidden = false,
            target = 25
        ),
        AchievementDefinition(
            id = "FOT_006",
            category = "Fotos",
            name = "Archivo visual",
            description = "Añadir 50 fotos",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Álbum grande",
            isHidden = false,
            target = 50
        ),
        AchievementDefinition(
            id = "FOT_007",
            category = "Fotos",
            name = "La foto del mes",
            description = "Añadir al menos una foto en un mes",
            difficulty = AchievementDifficulty.POCO_COMUN,
            points = 10,
            iconKey = "Calendario foto",
            isHidden = false,
            target = 1
        ),
        AchievementDefinition(
            id = "FOT_008",
            category = "Fotos",
            name = "Memoria espumosa",
            description = "Tener fotos en 5 meses distintos",
            difficulty = AchievementDifficulty.EPICO,
            points = 35,
            iconKey = "Mural",
            isHidden = false,
            target = 5
        ),
        AchievementDefinition(
            id = "COL_008",
            category = "Colección",
            name = "Colección Leyenda",
            description = "Completar GEN_007, GEN_009, GEN_011 y GEN_013",
            difficulty = AchievementDifficulty.LEGENDARIO,
            points = 50,
            iconKey = "Trofeo total",
            isHidden = false,
            target = 1
        )
    )
}
